export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGOUT = 'LOGOUT';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const GET_EVENT_NEWSFEED = 'GET_EVENT_NEWSFEED';
export const GET_EVENT_UPCOMING = 'GET_EVENT_UPCOMING';
export const GET_EVENT_CREATED_HISTORY = 'GET_EVENT_CREATED_HISTORY';
export const GET_EVENT_PARTICIPANT_HISTORY = 'GET_EVENT_PARTICIPANT_HISTORY';
export const GET_EVENT_VERIFIED_HISTORY = 'GET_EVENT_VERIFIED_HISTORY';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_POPUP_NOTIFICATION = 'SHOW_POPUP_NOTIFICATION';
export const HIDE_POPUP_NOTIFICATION = 'HIDE_POPUP_NOTIFICATION';
export const SHOW_POPUP_SELECTION = 'SHOW_POPUP_SELECTION';
export const HIDE_POPUP_SELECTION = 'HIDE_POPUP_SELECTION';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';

export const GET_ALL_POST = 'GET_ALL_POST';
